import {
  Branch,
  LicenseInfo,
  NotificationLog,
  RMATicket,
  UserProfile,
  WarrantyItem,
  WooCommerceOrder,
} from './types';

export const initialLicenseInfo: LicenseInfo = {
  license_key: 'THANHAUDIO-PRO-2026-X987K',
  domain: 'https://thanhaudio.vn',
  ip_address: '103.142.26.88',
  plugin_version: '3.5.0-PRO',
  status: 'active',
  license_type: 'Lifetime Pro',
  expiry_date: '2030-12-31',
  registered_to: 'Thành Audio Electronic JSC (thanhaudio.com.vn@gmail.com)',
  server_url: 'https://thanhaudio.vn/security',
  api_endpoint: 'https://thanhaudio.vn/security/api/v1/verify-license',
  last_verified_at: new Date().toISOString(),
  next_cron_check: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
  is_write_blocked: false,
};

export const initialBranches: Branch[] = [
  {
    id: 1,
    code: 'HN-CG',
    name: 'Thành Audio - Showroom Cầu Giấy (Trụ sở chính)',
    phone: '0987.654.321',
    address: 'Số 168 Cầu Giấy, Phường Quan Hoa, Quận Cầu Giấy, Hà Nội',
    manager_name: 'Nguyễn Văn Thành (GĐ)',
    email: 'hanoi@thanhaudio.vn',
    is_active: true,
    notes: 'Tổng kho và trung tâm bảo hành cấp 1 miền Bắc',
    total_warranties: 1240,
  },
  {
    id: 2,
    code: 'HCM-Q10',
    name: 'Thành Audio - Showroom Quận 10',
    phone: '0912.333.888',
    address: 'Số 452 Đường 3/2, Phường 12, Quận 10, TP. Hồ Chí Minh',
    manager_name: 'Lê Hoàng Nam (Trưởng CN)',
    email: 'hcm@thanhaudio.vn',
    is_active: true,
    notes: 'Trung tâm phân phối & bảo hành khu vực phía Nam',
    total_warranties: 890,
  },
  {
    id: 3,
    code: 'DN-HC',
    name: 'Thành Audio - Chi nhánh Đà Nẵng',
    phone: '0935.777.999',
    address: 'Số 88 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
    manager_name: 'Trần Đình Trọng',
    email: 'danang@thanhaudio.vn',
    is_active: true,
    notes: 'Showroom âm thanh karaoke & hội trường miền Trung',
    total_warranties: 420,
  },
  {
    id: 4,
    code: 'HP-LE',
    name: 'Đại lý Ủy quyền - Audio Pro Hải Phòng',
    phone: '0904.555.222',
    address: 'Số 12 Lạch Tray, Quận Ngô Quyền, TP. Hải Phòng',
    manager_name: 'Vũ Đức Hải',
    email: 'haiphong.partner@thanhaudio.vn',
    is_active: true,
    notes: 'Đại lý phân phối cấp Platinum',
    total_warranties: 235,
  },
  {
    id: 5,
    code: 'CT-NK',
    name: 'Đại lý Ủy quyền - Thành Audio Tây Đô Cần Thơ',
    phone: '0979.111.444',
    address: 'Số 95 Đại lộ Hòa Bình, Quận Ninh Kiều, TP. Cần Thơ',
    manager_name: 'Phạm Minh Quân',
    email: 'cantho.partner@thanhaudio.vn',
    is_active: true,
    notes: 'Đại lý khu vực Tây Nam Bộ',
    total_warranties: 180,
  },
];

export const userProfiles: UserProfile[] = [
  {
    id: 1,
    name: 'Nguyễn Văn Thành (Super Admin)',
    email: 'thanhaudio.com.vn@gmail.com',
    role: 'administrator',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 2,
    name: 'Lê Hoàng Nam (Quản lý Chi nhánh HCM)',
    email: 'nam.le@thanhaudio.vn',
    role: 'branch_manager',
    assigned_branch_id: 2,
    branch_name: 'Thành Audio - Showroom Quận 10',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 3,
    name: 'Trần Văn Kỹ (Trưởng Kỹ Thuật RMA)',
    email: 'kythuat.rma@thanhaudio.vn',
    role: 'technician',
    assigned_branch_id: 1,
    branch_name: 'Thành Audio - Showroom Cầu Giấy (Trụ sở chính)',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
];

export const initialWarranties: WarrantyItem[] = [
  {
    id: 1,
    serial_number: 'TA-JBL-2025-98214',
    sku: 'JBL-PASION-10',
    product_name: 'Loa Karaoke JBL Pasion 10 (Bass 25cm, 200W)',
    category: 'Loa Karaoke',
    purchase_date: '2025-11-15',
    warranty_months: 24,
    expiry_date: '2027-11-15',
    customer_name: 'Nguyễn Văn Hùng',
    customer_phone: '0901234567',
    customer_email: 'hung.nguyen88@gmail.com',
    customer_address: 'Số 45 Hoàng Hoa Thám, Ba Đình, Hà Nội',
    branch_id: 1,
    branch_name: 'Thành Audio - Showroom Cầu Giấy (Trụ sở chính)',
    branch_phone: '0987.654.321',
    branch_address: 'Số 168 Cầu Giấy, Phường Quan Hoa, Quận Cầu Giấy, Hà Nội',
    seller_name: 'Nguyễn Tuấn Anh',
    seller_phone: '0966.123.999',
    seller_role: 'Sale Staff',
    status: 'active',
    invoice_number: 'HD-2025-00891',
    notes: 'Kèm dây loa cao cấp & phiếu bảo hành chính hãng',
    woocommerce_order_id: 'WC-9821',
    created_at: '2025-11-15T09:30:00Z',
    rma_count: 0,
  },
  {
    id: 2,
    serial_number: 'TA-CRW-2024-11045',
    sku: 'CROWN-XLI-2500',
    product_name: 'Cục đẩy công suất Crown XLi 2500 (2 Kênh 750W)',
    category: 'Cục Đẩy Công Suất',
    purchase_date: '2024-03-10',
    warranty_months: 12,
    expiry_date: '2025-03-10',
    customer_name: 'Trần Thị Mai Phương',
    customer_phone: '0988776655',
    customer_email: 'phuong.tran@vietcombank.com.vn',
    customer_address: '12 Nguyễn Trãi, Quận 1, TP.HCM',
    branch_id: 2,
    branch_name: 'Thành Audio - Showroom Quận 10',
    branch_phone: '0912.333.888',
    branch_address: 'Số 452 Đường 3/2, Phường 12, Quận 10, TP. Hồ Chí Minh',
    seller_name: 'Đặng Quốc Huy',
    seller_phone: '0933.444.555',
    seller_role: 'Store Manager',
    status: 'expiring_soon',
    invoice_number: 'HD-2024-02314',
    notes: 'Khách mua lắp trọn gói phòng trà',
    woocommerce_order_id: 'WC-6430',
    created_at: '2024-03-10T14:15:00Z',
    rma_count: 1,
  },
  {
    id: 3,
    serial_number: 'TA-SHU-2025-77341',
    sku: 'SHURE-UGX23-PLUS',
    product_name: 'Micro Không Dây Shure UGX23 Plus (Chống hú rít 4 râu)',
    category: 'Micro',
    purchase_date: '2025-08-20',
    warranty_months: 12,
    expiry_date: '2026-08-20',
    customer_name: 'Hoàng Minh Tuấn',
    customer_phone: '0918223344',
    customer_email: 'tuan.hm@gmail.com',
    customer_address: 'Phường Hòa Thuận Đông, Quận Hải Châu, Đà Nẵng',
    branch_id: 3,
    branch_name: 'Thành Audio - Chi nhánh Đà Nẵng',
    branch_phone: '0935.777.999',
    branch_address: 'Số 88 Nguyễn Văn Linh, Quận Hải Châu, TP. Đà Nẵng',
    seller_name: 'Phan Minh Đức',
    seller_phone: '0944.555.666',
    seller_role: 'Sale Staff',
    status: 'active',
    invoice_number: 'HD-2025-04512',
    notes: 'Kèm đôi chống lăn & 4 pin sạc',
    woocommerce_order_id: 'WC-10452',
    created_at: '2025-08-20T10:00:00Z',
    rma_count: 0,
  },
  {
    id: 4,
    serial_number: 'TA-VSX-2023-45120',
    sku: 'VANG-SO-X6-PRO',
    product_name: 'Vang số cao cấp Tripath X6 Pro (DSP 64bit)',
    category: 'Vang Số / Vang Cơ',
    purchase_date: '2023-01-05',
    warranty_months: 24,
    expiry_date: '2025-01-05',
    customer_name: 'Bùi Đức Long',
    customer_phone: '0977889900',
    customer_email: 'longbui.arch@yahoo.com',
    customer_address: 'Khu Đô Thị Vinhomes Imperia, Hồng Bàng, Hải Phòng',
    branch_id: 4,
    branch_name: 'Đại lý Ủy quyền - Audio Pro Hải Phòng',
    branch_phone: '0904.555.222',
    branch_address: 'Số 12 Lạch Tray, Quận Ngô Quyền, TP. Hải Phòng',
    seller_name: 'Vũ Đức Hải',
    seller_phone: '0904.555.222',
    seller_role: 'Dealer Agent',
    status: 'expired',
    invoice_number: 'HD-2023-00109',
    notes: 'Đã hết hạn bảo hành tiêu chuẩn',
    woocommerce_order_id: 'WC-3190',
    created_at: '2023-01-05T16:20:00Z',
    rma_count: 0,
  },
  {
    id: 5,
    serial_number: 'TA-SUB-2025-66019',
    sku: 'BOSE-1200-SUB',
    product_name: 'Loa Sub Điện Siêu Trầm Bose 1200 (Bass 30cm, 500W)',
    category: 'Loa Subwoofer',
    purchase_date: '2025-12-01',
    warranty_months: 18,
    expiry_date: '2027-06-01',
    customer_name: 'Võ Thanh Tùng',
    customer_phone: '0939112233',
    customer_email: 'tung.vo@cantho.edu.vn',
    customer_address: 'Quận Ninh Kiều, TP. Cần Thơ',
    branch_id: 5,
    branch_name: 'Đại lý Ủy quyền - Thành Audio Tây Đô Cần Thơ',
    branch_phone: '0979.111.444',
    branch_address: 'Số 95 Đại lộ Hòa Bình, Quận Ninh Kiều, TP. Cần Thơ',
    seller_name: 'Phạm Minh Quân',
    seller_phone: '0979.111.444',
    seller_role: 'Dealer Agent',
    status: 'active',
    invoice_number: 'HD-2025-09102',
    notes: 'Bảo hành tận nơi 6 tháng đầu',
    woocommerce_order_id: 'WC-11002',
    created_at: '2025-12-01T11:45:00Z',
    rma_count: 0,
  },
  {
    id: 6,
    serial_number: 'TA-NEX-2025-33418',
    sku: 'NEX-FX8-II',
    product_name: 'Vang cơ lai số Nex Acoustics FX8 II (Bluetooth 5.0, Cổng Quang)',
    category: 'Vang Số / Vang Cơ',
    purchase_date: '2025-06-15',
    warranty_months: 12,
    expiry_date: '2026-06-15',
    customer_name: 'Phan Quốc Bảo',
    customer_phone: '0909654321',
    customer_email: 'bao.phan@gmail.com',
    customer_address: '228 Lê Duẩn, Hoàn Kiếm, Hà Nội',
    branch_id: 1,
    branch_name: 'Thành Audio - Showroom Cầu Giấy (Trụ sở chính)',
    branch_phone: '0987.654.321',
    branch_address: 'Số 168 Cầu Giấy, Phường Quan Hoa, Quận Cầu Giấy, Hà Nội',
    seller_name: 'Nguyễn Tuấn Anh',
    seller_phone: '0966.123.999',
    seller_role: 'Sale Staff',
    status: 'active',
    invoice_number: 'HD-2025-03112',
    notes: 'Kèm cáp quang Gold 2m',
    woocommerce_order_id: 'WC-8824',
    created_at: '2025-06-15T08:15:00Z',
    rma_count: 1,
  },
];

export const initialRMATickets: RMATicket[] = [
  {
    id: 1,
    ticket_code: 'RMA-2026-0042',
    serial_number: 'TA-CRW-2024-11045',
    sku: 'CROWN-XLI-2500',
    product_name: 'Cục đẩy công suất Crown XLi 2500',
    customer_name: 'Trần Thị Mai Phương',
    customer_phone: '0988776655',
    branch_id: 2,
    branch_name: 'Thành Audio - Showroom Quận 10',
    receiving_staff: 'Đặng Quốc Huy',
    technician_name: 'Lê Văn Hiếu',
    intake_date: '2026-02-10T09:00:00Z',
    status: 'repairing',
    fault_description: 'Kênh A bị ngắt rơ-le khi mở âm lượng lớn, đèn Protect nháy đỏ',
    accessories_included: 'Dây nguồn xịn, không hộp',
    technician_notes: 'Đã kiểm tra bo công suất kênh A, phát hiện chập 2 sò Toshiba 2SA1943. Đang thay thế và đo dòng tĩnh.',
    customer_notes: 'Đang tiến hành thay linh kiện công suất chính hãng. Dự kiến bàn giao ngày 15/02.',
    repair_cost: 350000,
    replaced_parts: ['Cặp sò công suất 2SA1943/2SC5200', 'Tụ lọc nguồn 10000uF'],
    priority: 'high',
    warranty_covered: true,
  },
  {
    id: 2,
    ticket_code: 'RMA-2026-0038',
    serial_number: 'TA-NEX-2025-33418',
    sku: 'NEX-FX8-II',
    product_name: 'Vang cơ lai số Nex Acoustics FX8 II',
    customer_name: 'Phan Quốc Bảo',
    customer_phone: '0909654321',
    branch_id: 1,
    branch_name: 'Thành Audio - Showroom Cầu Giấy (Trụ sở chính)',
    receiving_staff: 'Nguyễn Tuấn Anh',
    technician_name: 'Trần Văn Kỹ',
    intake_date: '2026-02-05T14:30:00Z',
    status: 'completed',
    completed_date: '2026-02-08T16:00:00Z',
    fault_description: 'Mất tiếng Echo ở cổng Mic 1, cổng Mic 2 hoạt động bình thường',
    accessories_included: 'Máy trần, kèm dây tín hiệu Canon',
    technician_notes: 'Lỏng chân chiết áp Echo Mic 1, đã hàn lại bo vi xử lý DSP và vệ sinh toàn bộ chiết áp.',
    customer_notes: 'Đã sửa xong và test ổn định 48h. Mời quý khách đến nhận máy tại Showroom Cầu Giấy.',
    repair_cost: 0,
    replaced_parts: ['Vệ sinh & bảo dưỡng mạch DSP'],
    priority: 'normal',
    warranty_covered: true,
  },
  {
    id: 3,
    ticket_code: 'RMA-2026-0029',
    serial_number: 'TA-JBL-2025-98214',
    sku: 'JBL-PASION-10',
    product_name: 'Loa Karaoke JBL Pasion 10',
    customer_name: 'Nguyễn Văn Hùng',
    customer_phone: '0901234567',
    branch_id: 1,
    branch_name: 'Thành Audio - Showroom Cầu Giấy (Trụ sở chính)',
    receiving_staff: 'Nguyễn Tuấn Anh',
    technician_name: 'Trần Văn Kỹ',
    intake_date: '2026-01-20T10:00:00Z',
    status: 'returned',
    completed_date: '2026-01-22T11:00:00Z',
    return_date: '2026-01-23T15:00:00Z',
    fault_description: 'Treble bên phải rè nhẹ khi chơi nhạc mạnh',
    accessories_included: 'Thùng xốp, ê-căng bảo vệ',
    technician_notes: 'Thay thế côn loa Treble Dome lụa chính hãng JBL. Đã bàn giao lại khách hàng ký nhận.',
    customer_notes: 'Đã hoàn tất bảo hành và trả lại khách hàng tận nơi.',
    repair_cost: 0,
    replaced_parts: ['Côn treble JBL Dome 3 inch'],
    priority: 'normal',
    warranty_covered: true,
  },
];

export const initialWooCommerceOrders: WooCommerceOrder[] = [
  {
    id: 'wc_ord_1',
    order_number: '#12890',
    customer_name: 'Đỗ Mạnh Cường',
    customer_phone: '0945678901',
    customer_email: 'cuong.dm@gmail.com',
    customer_address: '15 Tố Hữu, Nam Từ Liêm, Hà Nội',
    product_title: 'Loa Karaoke JBL Pasion 10 Chính Hãng',
    sku: 'JBL-PASION-10',
    total_amount: 14500000,
    status: 'completed',
    created_at: '2026-02-14T08:20:00Z',
    assigned_serial: 'TA-JBL-2026-10293',
    branch_id: 1,
    is_synced_to_warranty: true,
  },
  {
    id: 'wc_ord_2',
    order_number: '#12891',
    customer_name: 'Trần Đình Quân',
    customer_phone: '0912998877',
    customer_email: 'quan.tran@vietjetair.com',
    customer_address: '88 Bạch Đằng, Tân Bình, TP.HCM',
    product_title: 'Cục đẩy công suất Crown XLi 2500',
    sku: 'CROWN-XLI-2500',
    total_amount: 11200000,
    status: 'processing',
    created_at: '2026-02-15T11:10:00Z',
    branch_id: 2,
    is_synced_to_warranty: false,
  },
  {
    id: 'wc_ord_3',
    order_number: '#12892',
    customer_name: 'Phạm Thị Thúy',
    customer_phone: '0983112244',
    customer_email: 'thuy.pham@techcombank.com.vn',
    customer_address: '45 Lê Lợi, TP. Đà Nẵng',
    product_title: 'Micro Không Dây Shure UGX23 Plus',
    sku: 'SHURE-UGX23-PLUS',
    total_amount: 3200000,
    status: 'pending',
    created_at: '2026-02-15T14:45:00Z',
    branch_id: 3,
    is_synced_to_warranty: false,
  },
];

export const initialNotifications: NotificationLog[] = [
  {
    id: 'notif_1',
    type: 'zalo_zns',
    recipient: '0901234567 (Nguyễn Văn Hùng)',
    template: 'ZNS_KICH_HOAT_BAO_HANH_THANH_CONG',
    trigger: 'activation_success',
    title: 'Kích hoạt bảo hành điện tử thành công',
    content: 'Thành Audio kính chào Quý khách! Sản phẩm Loa JBL Pasion 10 (Serial: TA-JBL-2025-98214) đã được kích hoạt bảo hành thành công đến 15/11/2027. Điểm mua: Showroom Cầu Giấy (Hotline: 0987.654.321). Tra cứu tại thanhaudio.vn/baohanh',
    status: 'delivered',
    timestamp: '2025-11-15T09:32:00Z',
  },
  {
    id: 'notif_2',
    type: 'sms',
    recipient: '0988776655 (Trần Thị Mai Phương)',
    template: 'SMS_RMA_STATUS_UPDATE',
    trigger: 'rma_status_change',
    title: 'Cập nhật tiến trình sửa chữa RMA #RMA-2026-0042',
    content: '[THANHAUDIO] Phiếu tiếp nhận RMA-2026-0042 (Cục đẩy Crown XLi 2500) đã chuyển sang trạng thái: ĐANG SỬA CHỮA tại Showroom Quận 10. Hotline Kỹ thuật: 0912.333.888.',
    status: 'delivered',
    timestamp: '2026-02-10T10:15:00Z',
  },
  {
    id: 'notif_3',
    type: 'email',
    recipient: 'phuong.tran@vietcombank.com.vn',
    template: 'EMAIL_CANH_BAO_SAP_HET_HAN',
    trigger: 'expiring_soon',
    title: 'Nhắc nhở: Sản phẩm âm thanh của bạn sắp hết hạn bảo hành (còn 15 ngày)',
    content: 'Chào bạn Trần Thị Mai Phương, thiết bị Crown XLi 2500 của bạn sẽ hết hạn bảo hành vào 10/03/2025. Liên hệ Thành Audio Quận 10 (0912.333.888) nếu bạn cần bảo dưỡng hoặc gia hạn gói bảo hành VIP.',
    status: 'sent',
    timestamp: '2025-02-23T08:00:00Z',
  },
];

export const INITIAL_LICENSE = initialLicenseInfo;
export const INITIAL_BRANCHES = initialBranches;
export const INITIAL_USERS = userProfiles;
export const INITIAL_WARRANTIES = initialWarranties;
export const INITIAL_RMA_TICKETS = initialRMATickets;
export const INITIAL_WOOCOMMERCE_ORDERS = initialWooCommerceOrders;
export const INITIAL_NOTIFICATIONS = initialNotifications;

